a <- read.csv("C:/Users/M/Desktop/爬虫/2016.csv",header=TRUE)	
b <- read.csv("C:/Users/M/Desktop/爬虫/2017.csv",header=TRUE)
br1=seq(0,500,5)
hist(a$marks,breaks=br1,col="red")
hist(b$marks,breaks=br1)